import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import localFont from "next/font/local";

const geistSans = localFont({
    src: "../public/fonts/Geist-Regular.woff2",
    variable: "--font-geist-sans",
    display: "swap",
});

const geistMono = localFont({
    src: "../public/fonts/GeistMono-Regular.woff2",
    variable: "--font-geist-mono",
    display: "swap",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
        <Navbar/>
        {children}
        <div className="w-full h-2 bg-[#DD773F]"></div>
        <Footer/>
        </body>
        </html>
    );
}
